# When adding a command to history, remove all previous duplicates first.
setopt HIST_IGNORE_ALL_DUPS

# Do not store a command if it is the same as the previous history entry.
setopt HIST_IGNORE_DUPS

# Do not store commands that start with a space in history.
setopt HIST_IGNORE_SPACE


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto, if installed.
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# Customize to your needs...
# Source PowerLevel 10k, if it exists.
[[ -s ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Source interactive startup script, if it exists.
[[ -s ~/.zsh-interactive-startup ]] && source ~/.zsh-interactive-startup

# Source custom interactive post-startup script, if it exists.
[[ -s ~/.custom-interactive-post-startup ]] && source ~/.custom-interactive-post-startup
